import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Merienda,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/src/components/smoothscroll";
import ScrollToTop from "@/src/components/scroll-to-top";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="lenis">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${merienda.variable} ${playfairDisplay.variable} antialiased`}
      >
        <ScrollToTop />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
